simple:
  hosts:
    172.16.120.201:
  vars:
    ansible_ssh_private_key_file: ~/.ssh/vagrant
    ansible_user: vagrant
    
kali-cluster:
  hosts:
    172.16.120.201:
    172.16.120.202:
    172.16.120.203:
  vars:
    ansible_ssh_private_key_file: ~/.ssh/vagrant
    ansible_user: vagrant
   
